# Custom Language File for Launcher Customizer

[ejs.app]
title = "WaferMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/WaferMC-Plugins"
mediaTwitchURL = "https://twitch.wafermc.it"
mediaInstagramURL = "https://www.instagram.com/propriowafer/"
mediaYouTubeURL = "https://www.youtube.com/@propriowafer"
mediaDiscordURL = "https://discord.wafermc.it"

[ejs.settings]
sourceGithub = "GitHub"
sourceGithubLink = "https://github.com/WaferMC-Plugins/WaferMC-Launcher"
support = "Discord"
supportLink = "https://discord.wafermc.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO SU WESTEROSCRAFT"
welcomeDescription = "La nostra missione e ricreare l'universo immaginato dall'autore George RR Martin nella sua serie fantasy, A Song of Ice and Fire. Attraverso lo sforzo collaborativo di migliaia di membri della community, abbiamo cercato di creare Westeros nel modo piu accurato e preciso possibile dentro Minecraft. Il mondo che stiamo creando e tuo da esplorare. Viaggia da Dorne a Castle Black e, se non hai paura, anche oltre la Barriera, ma non aspettare troppo. Come avverte in modo inquietante il motto di Casa Stark: Winter is Coming."
welcomeDescCTA = "Ti separano solo pochi clic da Westeros."
