# Custom Language File for Launcher Customizer

[ejs.app]
title = "WaferMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/WaferMC-Plugins"
mediaTwitchURL = "https://twitch.wafermc.it"
mediaInstagramURL = "https://www.instagram.com/propriowafer/"
mediaYouTubeURL = "https://www.youtube.com/@propriowafer"
mediaDiscordURL = "https://discord.wafermc.it"

[ejs.settings]
sourceGithub = "GitHub"
sourceGithubLink = "https://github.com/WaferMC-Plugins/WaferMC-Launcher"
support = "Discord"
supportLink = "https://discord.wafermc.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO SU WAFERMC"
welcomeDescription = "WaferMC Launcher è il client ufficiale per giocare sul server WaferMC. Troverai un ambiente gia configurato con mod, impostazioni e dipendenze pronte all'uso, così puoi entrare subito senza setup manuale. A ogni avvio il launcher controlla e aggiorna automaticamente i file necessari, per offrirti compatibilità con il server, stabilità e prestazioni migliori."
welcomeDescCTA = "Ti separano solo pochi clic da WaferMC."
